"""Create tables owners, pets

Revision ID: 282c9cdde08a
Revises: f520dd246110
Create Date: 2024-01-09 10:10:37.015509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282c9cdde08a'
down_revision = 'f520dd246110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
